### ISSUE TITLE
Add installation via npm

### ISSUE THREAD

**Issue by mswiecicki** [4rlekin/ng-simple-modal#2]
I don't think there is need to explain.

One thing though - how one would require angular module ?

**Comment by piecioshka** [comment]
@4rlekin you should create package.json file, and put list of deps in "dependencies" key.
More details here: https://docs.npmjs.com/files/package.json

**Comment by 4rlekin** [comment]
Yup, that's not the issue here, i even read article today about publishing npm packages.

What im wondering about is - how one can use npm package to import angular module ?? 
Honestly, how one can even export angular module... Of course the module could expose only service method, and then require it like: `.factory('modal', require('simple-modal'))` or something like that, but in such case there would be major inconsistency between the "file installation" and "npm installation"

I need to take a peek how some other modules deal with that

**Comment by mswiecicki** [comment]
@piecioshka oh well... i guess im just tired... for some reason i fathomed that when used as npm package i'd have to require it somehow, and then i started wondering how could i require the package into angular module system....

I mistook it with node... Awkward :/

**Comment by piecioshka** [comment]
We should meet on some tea sometime 😄

**Comment by mswiecicki** [comment]
@piecioshka should be easy enough, when is the next meetup? ;P

**Comment by piecioshka** [comment]
14 of December at Państwomiasto.
